version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/homelight/lidder

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go run lidder.go sample_config.yml
